language: node_js

cache: yarn

node_js:
- 'stable'

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true
